In [5]:
#Operator overriding
# class Demo:
#     def add(self,n1,n2):
#         print(n1+n2)
#     def add(self,n1,n2,n3):
#         print(n1+n2+n3)
# d=Demo()
# d.add(15,20,30)

#Operator overloading
class Demo:
    def __init__(self,x,y):
        self.x=x
        self.y=y
    def __str__(self):
        return "X "+str(self.x)+" Y "+str(self.y)  
    def __add__(self,other):
        x=self.x+other.x
        y=self.y+other.y
        return Demo(x,y)
    def __sub__(self,other):
        x=self.x-other.x
        y=self.y-other.y
        return Demo(x,y)
    def __mul__(self,other):
        x=self.x*other.x
        y=self.y*other.y
        return Demo(x,y)
    def __truediv__(self,other):
        x=self.x/other.x
        y=self.y/other.y
        return Demo(x,y)
    def __floordiv__(self,other):
        x=self.x//other.x
        y=self.y//other.y
        return Demo(x,y)
    def __mod__(self,other):
        x=self.x%other.x
        y=self.y%other.y
        return Demo(x,y)
    def __pow__(self,other):
        x=self.x**other.x
        y=self.y**other.y
        return Demo(x,y)
    def __lt__(self,other):
        x=self.x<other.x
        y=self.y<other.y
        return Demo(x,y)
    def __gt__(self,other):
        x=self.x>other.x
        y=self.y>other.y
        return Demo(x,y)
    def __ge__(self,other):
        x=self.x>=other.x
        y=self.y>=other.y
        return Demo(x,y)
    def __le__(self,other):
        x=self.x<=other.x
        y=self.y<=other.y
        return Demo(x,y)
    def __ne__(self,other):
        x=self.x!=other.x
        y=self.y!=other.y
        return Demo(x,y)
    def __eq__(self,other):
        x=self.x==other.x
        y=self.y==other.y
        return Demo(x,y)
d=Demo(6,31)
d1=Demo(3,4)
print(d+d1)
print(d-d1)
print(d*d1)
print(d/d1)
print(d//d1)
print(d%d1)
print(d**d1)
print(d>d1)
print(d<d1)
print(d>=d1)
print(d<=d1)
print(d!=d1)
# sub subtract
# mul multiply
# truediv  true division
# floordiv  floor division
# mod
# pow
# lt for less than
# gt for greater than
# ge for greater than and equals to
# le for less than and equals to
# ne not equals to
# eq for double equals to

X 9 Y 35
X 3 Y 27
X 18 Y 124
X 2.0 Y 7.75
X 2 Y 7
X 0 Y 3
X 216 Y 923521
X True Y True
X False Y False
X True Y True
X False Y False
X True Y True


In [7]:
#create class student with following attributes rollNo name age and total marks
#create suitable methods for reading and printing members variables 
#wap to overload == equal operator to print the details of students having same marks
class Student:
    def __init__(self,roll,name,age,marks):
        self.roll=roll
        self.name=name
        self.age=age
        self.marks=marks
    def display(self):
        print(self.roll)
        print(self.name)
        print(self.age)
        print(self.marks)
    def __eq__(self,other):
        return self.marks==other.marks
s=Student(14,"Sahil",20,95)
s1=Student(30,"Sujal",20,95)
if(s==s1):
    print("Both are equals")
else:
    print("Bot are not equal")

Both are equals


In [8]:
#types of inheritance
#1 Simple inheritance
# class Parent:
#     def f1(self):
#         print("hello parent")
# class child(Parent):
#     def f2(self):
#         print("hello Child")
# c=child()
# c.f2()

#2 Multiple Inheritance
# class Parent:
#     def f1(self):
#         print("Parent 1")
# class Parent1:
#     def f2(self):
#         print("Parent 2")
# class Parent2:
#     def f2(self):
#         print("Parent 3")
# class Child(Parent,Parent1,Parent2):  #Jo parent phele order me milega ussika method print karayega 
#     def f3(self):
#         print("Child")
# c=Child()
# c.f1()
# c.f2()
# print(Child.__mro__)

#Multilevel Inheritance -
# class GrandParent:
#     def f1(self):
#         print("Grand Parent")
# class Parent(GrandParent):
#     def f2(self):
#         print("Parent")
# class Child(Parent):
#     def f3(self):
#         print("Child")
# c=Child()
# c.f1()

#Hierarchical Inheritance
# class Parent:
#     def f1(self):
#         print("Parent")
# class Child1(Parent):
#     def f2(self):
#         print("Child 1")
# class Child2(Parent):
#     def f3(self):
#         print("Child 2")
# c=Child2()
# c.f3()

#Hybrid Inheritance
# class Parent:
#     def f1(self):
#         print("Parent 1")
# class Child(Parent):
#     def f2(self):
#         print("Child ")
# class Parent1:
#     def f3(self):
#         print("Parent 2")
# class Child1(child,Parent1):
#     def f4(self):
#         print("Child 2")
# c=Child1()
# c.f1()

#Diamond Inheritance
class A:
    def f1(self):
        print("A")
class B(A):
    def f2(self):
        print("B")
class C(A):
    def f3(self):
        print("C")
class D(B,C):
    def f4(self):
        print("D")
d=D()
d.f1()

A


In [9]:
#WAPP That has class Point and location as Child class of point find reflection of point about x axis
#reflection method define in location class
class Point:
    def __init__(self,x,y):
        self.x=x
        self.y=y
class Location(Point):
    def reflection(self):
        return self.x ,0-self.y
l=Location(2,-2)
print(l.reflection())

(2, 2)


In [10]:
class Parent:
    def f1(self):
        print("Parent 1")
class Parent1():
    def f2(self):
        print("Parent 2")
class Parent2():
    def f3(self):
        print("Parent 3")
class Child(Parent,Parent1,Parent2):  #Jo parent phele order me milega ussika method print karayega 
    def f4(self):
        print("Child")
c=Child()
c.f1()
c.f2()
print(Child.__mro__)


Parent 1
Parent 2
(<class '__main__.Child'>, <class '__main__.Parent'>, <class '__main__.Parent1'>, <class '__main__.Parent2'>, <class 'object'>)


In [11]:
class Parent:
    def display(self):
        print("Hello Parent")
class Child(Parent):
    def display(self):
        super().display()
        print("Hello Child")
c = Child()
c.display()

Hello Parent
Hello Child


In [14]:
# Implement the following heirarchy create class called staff having name and salary as its attribute
# Derived class teaching has subject name as its attribute and non teaching class department name as its attribute
# the derive class methods override the methods of the base class
class Staff:
    def __init__(self,name,salary):
        self.name = name
        self.salary = salary
    def display(self):
        print("Name:",self.name)
        print("Salary:",self.salary)
class Teaching(Staff):
    def __init__(self,name,salary,subject):
        super().__init__(name,salary)
        self.subject = subject
    def display(self):
        super().display()
        print("Subject:",self.subject)
class NonTeaching(Staff):
    def __init__(self,name,salary,department):
        super().__init__(name,salary)
        self.department = department
    def display(self):
        super().display()
        print("Department:",self.department)
t = Teaching("ABP",100000,"Physics")
n = NonTeaching("Hitesh",10,"Cleaning")
t.display()
n.display()

Name: ABP
Salary: 100000
Subject: Physics
Name: Hitesh
Salary: 10
Department: Cleaning


In [20]:
# wap that has classes such as student,course,department,enroll and this should be displayed:
#     Raj with roll no 101 has enrolled for fcsp-1 in ce department
class Department(Course):
    def __init__(self,dept):
        self.dept = dept
class Course(Department):
    def __init__(self,course,dept):
        super().__init__(dept)
        self.course = course
class Student:
    def __init__(self,name,rollno):
        self.name = name
        self.rollno = rollno
class Enroll(Student,Course):
    def __init__(self,name,rollno,course,dept):
        Student.__init__(self,name,rollno)
        Course.__init__(self,course,dept)
    def display(self):
        print(f"{self.name} with rollno {self.rollno} has enrolled for {self.course} in {self.dept} department")
e = Enroll("Raj","101","FCSP-1","CE")
e.display()

Raj with rollno 101 has enrolled for FCSP-1 in CE department


In [6]:
# Create class called Stduent having name and email as its attribute
# create another class called PHDguide should have 4 methods
# constructor,display,add,remove
# In phd class having name email and student as its attributes
class Student:
    def __init__(self,name,email):
        self.name = name
        self.email = email
class PhdGuide:
    def __init__(self):
        self.l = []
    def add(self,st):
        self.l.append(st.name)
    def remove(self,name):
        self.l.remove(name)
    def display(self):
        for i in self.l:
            print(i)
a = Student("Raj","raj@123")
b = Student("Sunny","sunny@456")
c = Student("Mohan","mohan@345")
p = PhdGuide()
p.add(a)
p.add(b)
p.add(c)
p.display()
p.remove("Raj")
p.display()

Raj
Sunny
Mohan
Sunny
Mohan


In [12]:
# Numpy arrays
# create numpy
import numpy as np
a = np.array([1,2,3,4])
print(a)
#Dimension in array
#0D Array Individual values are counted as 0d array
#1D Array (above example is 1d array)
#2D Array
b = np.array([[1,2],[3,4],[5,6]])
print(b)
#3D Array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
#Higher dimensional array
d = np.array([1,2,3,4],ndmin= 5)
print(d)
print(d.ndim) #ndmin creates array of n dimensions and ndim returns number of dimensions of specific array

[1 2 3 4]
[[1 2]
 [3 4]
 [5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[[[1 2 3 4]]]]]
5


In [20]:
#Numpy array slicing (the solutions obtained were the questions)
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print("*********** 1D Array ***************")
print(a[2:5])
print(a[-3:-1])
print(a[-2::-2])
print(a[5::-2])
print("*********** 2D Array ***************")
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b[1,1:4])
print(b[:,2])
print(b[:,-2:0:-1])
print(b[:,3:0:-1])
print("************ 3D Array ****************")
c = np.array([[[1,2,3,4,],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]],[[17,18,19,20],[21,22,23,24]]])
print(c[2,0,2],c[-1,-2,-2]) #can use various combination from both of these indexes eg. -1,0,2
print(c[2,0,-2:-4:-1]) #also has various combinations you can use // check all the options thoroughly in exam
print(c[0,:,-2::-2])
print(c[1:,:,1::2])

*********** 1D Array ***************
[3 4 5]
[5 6]
[6 4 2]
[6 4 2]
*********** 2D Array ***************
[7 8 9]
[3 8]
[[4 3 2]
 [9 8 7]]
[[4 3 2]
 [9 8 7]]
************ 3D Array ****************
19 19
[19 18]
[[3 1]
 [7 5]]
[[[10 12]
  [14 16]]

 [[18 20]
  [22 24]]]


In [59]:
#numpy array shape
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print(a.shape)
#numpy array reshaping
#reshape from 1d to 2d
b = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
c = b.reshape(2,6) # multiplication of both the values should be equal to length of original array. Format is (rows,cols)
print(c)
#unknown dimension
d = b.reshape(3,2,-1) # when one dimension is not known, -1 is used so the method finds the remaining dimension on its own
print(d)
#flattening the array
e = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(e.reshape(-1))
#concatenating 1d array
a1 = np.array([1,2,3,4])
a2 = np.array([5,6,7,8])
print(np.concatenate((a1,a2)))
#concatenating 2d array
a3 = np.array([[1,2],[3,4]])
a4 = np.array([[5,6],[7,8]])
print(np.concatenate((a3,a4),axis=0))
print(np.concatenate((a3,a4),axis=1))
#concatenating 3d array
a5 = np.array([[[1,2,3,4],[5,6,7,8]],[[9,10,11,12],[13,14,15,16]]])
a6 = np.array([[[17,18,19,20],[21,22,23,24]],[[25,26,27,28],[29,30,31,32]]])
print(np.concatenate((a5,a6),axis=0))
print(np.concatenate((a5,a6),axis=1))
print(np.concatenate((a5,a6),axis=2))
#numpy splitting array
a7 = np.array([1,2,3,4,5,6])
print(np.array_split(a7,3))
#splitting 2d array
a8 = np.array([[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]])
print(np.array_split(a8,3,axis = 1))

(2, 3)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]
[1 2 3 4 5 6 7 8]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]
[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]

 [[25 26 27 28]
  [29 30 31 32]]]
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [17 18 19 20]
  [21 22 23 24]]

 [[ 9 10 11 12]
  [13 14 15 16]
  [25 26 27 28]
  [29 30 31 32]]]
[[[ 1  2  3  4 17 18 19 20]
  [ 5  6  7  8 21 22 23 24]]

 [[ 9 10 11 12 25 26 27 28]
  [13 14 15 16 29 30 31 32]]]
[array([1, 2]), array([3, 4]), array([5, 6])]
[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]]), array([], shape=(6, 0), dtype=int32)]


In [72]:
# Where function (Returns index number of element in array)
a = np.array([1,2,3,4,5,6,7,8,9])
print(np.where(a==1))
a = np.array([1,1,2,3,4,1,4,6])
print(np.where(a==1))
print(np.where(a%2 == 0))
#numpy sorting array
#sorting 1d array
a = np.array([3,2,0,1])
print(np.sort(a))
print(np.sort(a)[::-1])
a = np.array(["q","c","b"])
print(np.sort(a))
a = np.array([True,False,True])
print(np.sort(a))
a = np.array([[3,2,4],[5,0,1]])
print(np.sort(a))
print(np.sort(a)[:,::-1])
a = np.array([[[3,2,4],[5,0,1]],[[3,1,2],[5,0,3]]])
print(np.sort(a))

(array([0], dtype=int64),)
(array([0, 1, 5], dtype=int64),)
(array([2, 4, 6, 7], dtype=int64),)
[0 1 2 3]
[3 2 1 0]
['b' 'c' 'q']
[False  True  True]
[[2 3 4]
 [0 1 5]]
[[4 3 2]
 [5 1 0]]
[[[2 3 4]
  [0 1 5]]

 [[1 2 3]
  [0 3 5]]]


In [81]:
# wap to convert the value of farenheit degrees into celcius degrees the array to be considered is for farenheit value:
#     [0,12,45.21,34,99.91,32]
# after converting numpy array into celcius, sort the array and find the position of 0.0.
import numpy as np
f = np.array([0,12,45.21,34,99.91,32])
c = (5/9)*(f-32)
x = np.sort(c)
print(x)
print(np.where(x==0.0))

[-17.77777778 -11.11111111   0.           1.11111111   7.33888889
  37.72777778]
(array([2], dtype=int64),)


In [83]:
# wap to return odd rows and even columns from below numpy array
import numpy as np
a = np.array([[3,6,9,12],[15,18,21,24],[27,30,33,36],[39,42,45,48],[51,54,57,60]])
print(a[1::2,::2])

[[15 21]
 [39 45]]


In [85]:
# create 5*2 array from range between  100 and 200 and difference between each element is 10
import numpy as np
a = np.arange(101,201,10)
print(a.reshape(5,2))

[[101 111]
 [121 131]
 [141 151]
 [161 171]
 [181 191]]


In [1]:
#Abstract Class
#Syntax
from abc import ABC,abstractmethod
class Demo(ABC):
    @abstractmethod
    def abstract_method(self):
        pass

In [3]:
from abc import ABC,abstractmethod
class Shape(ABC):
    def __init__(self,shape_name):
        self.shape_name = shape_name
    @abstractmethod
    def draw(self):
        pass
class Rectangle(Shape):
    def __init__(self):
        super().__init__("Rectangle")
    def draw(self):
        print("This is",self.shape_name)
class Circle(Shape):
    def __init__(self):
        super().__init__("Circle")
    def draw(self):
        print("This is",self.shape_name)
r = Rectangle()
c = Circle()
r.draw()
c.draw()

This is Rectangle
This is Circle


In [4]:
# Create an abstract class named shape. Create an abstract method named calculate_area. Create two classes named rectangle
# and circle which inherits shape class. Create calculate_area method in rectangle class, it should return area of the
# rectangle object. Create calculate_area method in circle class, it should return area of the circle object. The program
# should also check whether the area of rectangle object is greater than another rectangle object by operator overloading
#Execute method resolution order of the circle class
from abc import ABC,abstractmethod
import math
class Shape(ABC):
    @abstractmethod
    def calculate_area(self):
        pass
class Rectangle(Shape):
    def __init__(self,l,b):
        self.l = l
        self.b = b
    def calculate_area(self):
        return self.l*self.b
    def __gt__(self,other):
        return self.calculate_area() > other.calculate_area()
class Circle(Shape):
    def __init__(self,r):
        self.r = r
    def calculate_area(self):
        return 2*math.pi*self.r
r1 = Rectangle(3,4)
c = Circle(4)
r2 = Rectangle(4,5)
print(r1.calculate_area())
print(r2.calculate_area())
print(c.calculate_area())
print(r1>r2)
print(Circle.__mro__)

12
20
25.132741228718345
False
(<class '__main__.Circle'>, <class '__main__.Shape'>, <class 'abc.ABC'>, <class 'object'>)


In [8]:
# wap to find the net salary of employee using inheritance. Create 3 classes employee, perks, net salary. Make employee
# class as an abstract class, it should have method for following tasks:
#     1)To get employee details like emp id, name, salary from user
#     2)To print employee details
#     3)Return salary
#     4)Define an abstract method employee_id
# Perks class should have method for following tasks:
#     1)To calculate DA,HRA and PF (all calculated using base salary)
#     2)To print individual and total perks
# Net Salary should have following tasks:
#     1)Calculate total salary after perks
#     2)Print employee detail with da,hra,pf and net salary
#     note: da is 35%, hra is 17% and pf is 12%
from abc import ABC,abstractmethod
class Employee(ABC):
    def __init__(self):
        self.emp_id = int(input("Enter Employee ID: "))
        self.name = input("Enter Name: ")
        self.salary = int(input("Enter Salary: "))
    def employee_details(self):
        print("Employee ID:",self.emp_id)
        print("Name:",self.name)
        print("Salary:",self.salary)
    def salary_detail(self):
        return self.salary
    @abstractmethod
    def employee_id(self):
        pass
class Perks(Employee):
    def __init__(self):
        super().__init__()
        self.da = self.hra = self.pf = 0
    def calculate_perks(self):
        self.da = self.salary*0.35
        self.hra = self.salary*0.17
        self.pf = self.salary*0.12
    def display_perks(self):
        self.calculate_perks()
        super().employee_details()
        print("DA:",self.da)
        print("HRA:",self.hra)
        print("PF:",self.pf)
        print("Total Perks:",(self.da+self.hra-self.pf))
    def employee_id(self):
        return self.emp_id
class Net_Salary(Perks):
    def __init__(self):
        super().__init__()
    def totalsal(self):
        return self.salary+self.da+self.hra-self.pf
    def employee_details(self):
        super().display_perks()
        print("Net Salary:",self.totalsal())
n = Net_Salary()
n.employee_details()

Enter Employee ID: 1
Enter Name: ABC
Enter Salary: 35000
Employee ID: 1
Name: ABC
Salary: 35000
DA: 12250.0
HRA: 5950.0
PF: 4200.0
Total Perks: 14000.0
Net Salary: 49000.0


In [14]:
# wap to create bus child class that inherits from the vehicle class. In vehicle class vehicle name, mileage, seating
# capacity as its data member. The default fare charge of any vehicle is seating capacity*100. If vehicle is bus instance
# we need to extra 10% on full fare as a maintainance charge.
class Vehicle:
    def __init__(self,name,mileage,cap):
        self.name = name
        self.mileage = mileage
        self.cap = cap
        self.fare = self.cap*100
    def fare_rate(self):
        if self.name == "Bus":
            return self.fare+self.fare*0.1
        return self.fare
    def display(self):
        print("Vehicle:",self.name)
        print("Mileage:",self.mileage)
        print("Seating Capacity:",self.cap)
        print("Fare:",self.fare_rate())
class Bus(Vehicle):
    def __init__(self,mileage,cap):
        super().__init__("Bus",mileage,cap)
v = Vehicle("Car",15,5)
b = Bus(20,100)
b.display()
v.display()

Vehicle: Bus
Mileage: 20
Seating Capacity: 100
Fare: 11000.0
Vehicle: Car
Mileage: 15
Seating Capacity: 5
Fare: 500
