In [5]:
#Operator overriding
# class Demo:
#     def add(self,n1,n2):
#         print(n1+n2)
#     def add(self,n1,n2,n3):
#         print(n1+n2+n3)
# d=Demo()
# d.add(15,20,30)

#Operator overloading
class Demo:
    def __init__(self,x,y):
        self.x=x
        self.y=y
    def __str__(self):
        return "X "+str(self.x)+" Y "+str(self.y)  
    def __add__(self,other):
        x=self.x+other.x
        y=self.y+other.y
        return Demo(x,y)
    def __sub__(self,other):
        x=self.x-other.x
        y=self.y-other.y
        return Demo(x,y)
    def __mul__(self,other):
        x=self.x*other.x
        y=self.y*other.y
        return Demo(x,y)
    def __truediv__(self,other):
        x=self.x/other.x
        y=self.y/other.y
        return Demo(x,y)
    def __floordiv__(self,other):
        x=self.x//other.x
        y=self.y//other.y
        return Demo(x,y)
    def __mod__(self,other):
        x=self.x%other.x
        y=self.y%other.y
        return Demo(x,y)
    def __pow__(self,other):
        x=self.x**other.x
        y=self.y**other.y
        return Demo(x,y)
    def __lt__(self,other):
        x=self.x<other.x
        y=self.y<other.y
        return Demo(x,y)
    def __gt__(self,other):
        x=self.x>other.x
        y=self.y>other.y
        return Demo(x,y)
    def __ge__(self,other):
        x=self.x>=other.x
        y=self.y>=other.y
        return Demo(x,y)
    def __le__(self,other):
        x=self.x<=other.x
        y=self.y<=other.y
        return Demo(x,y)
    def __ne__(self,other):
        x=self.x!=other.x
        y=self.y!=other.y
        return Demo(x,y)
    def __eq__(self,other):
        x=self.x==other.x
        y=self.y==other.y
        return Demo(x,y)
d=Demo(6,31)
d1=Demo(3,4)
print(d+d1)
print(d-d1)
print(d*d1)
print(d/d1)
print(d//d1)
print(d%d1)
print(d**d1)
print(d>d1)
print(d<d1)
print(d>=d1)
print(d<=d1)
print(d!=d1)
# sub subtract
# mul multiply
# truediv  true division
# floordiv  floor division
# mod
# pow
# lt for less than
# gt for greater than
# ge for greater than and equals to
# le for less than and equals to
# ne not equals to
# eq for double equals to

X 9 Y 35
X 3 Y 27
X 18 Y 124
X 2.0 Y 7.75
X 2 Y 7
X 0 Y 3
X 216 Y 923521
X True Y True
X False Y False
X True Y True
X False Y False
X True Y True


In [7]:
#create class student with following attributes rollNo name age and total marks
#create suitable methods for reading and printing members variables 
#wap to overload == equal operator to print the details of students having same marks
class Student:
    def __init__(self,roll,name,age,marks):
        self.roll=roll
        self.name=name
        self.age=age
        self.marks=marks
    def display(self):
        print(self.roll)
        print(self.name)
        print(self.age)
        print(self.marks)
    def __eq__(self,other):
        return self.marks==other.marks
s=Student(14,"Sahil",20,95)
s1=Student(30,"Sujal",20,95)
if(s==s1):
    print("Both are equals")
else:
    print("Bot are not equal")

Both are equals


In [8]:
#types of inheritance
#1 Simple inheritance
# class Parent:
#     def f1(self):
#         print("hello parent")
# class child(Parent):
#     def f2(self):
#         print("hello Child")
# c=child()
# c.f2()

#2 Multiple Inheritance
# class Parent:
#     def f1(self):
#         print("Parent 1")
# class Parent1:
#     def f2(self):
#         print("Parent 2")
# class Parent2:
#     def f2(self):
#         print("Parent 3")
# class Child(Parent,Parent1,Parent2):  #Jo parent phele order me milega ussika method print karayega 
#     def f3(self):
#         print("Child")
# c=Child()
# c.f1()
# c.f2()
# print(Child.__mro__)

#Multilevel Inheritance -
# class GrandParent:
#     def f1(self):
#         print("Grand Parent")
# class Parent(GrandParent):
#     def f2(self):
#         print("Parent")
# class Child(Parent):
#     def f3(self):
#         print("Child")
# c=Child()
# c.f1()

#Hierarchical Inheritance
# class Parent:
#     def f1(self):
#         print("Parent")
# class Child1(Parent):
#     def f2(self):
#         print("Child 1")
# class Child2(Parent):
#     def f3(self):
#         print("Child 2")
# c=Child2()
# c.f3()

#Hybrid Inheritance
# class Parent:
#     def f1(self):
#         print("Parent 1")
# class Child(Parent):
#     def f2(self):
#         print("Child ")
# class Parent1:
#     def f3(self):
#         print("Parent 2")
# class Child1(child,Parent1):
#     def f4(self):
#         print("Child 2")
# c=Child1()
# c.f1()

#Diamond Inheritance
class A:
    def f1(self):
        print("A")
class B(A):
    def f2(self):
        print("B")
class C(A):
    def f3(self):
        print("C")
class D(B,C):
    def f4(self):
        print("D")
d=D()
d.f1()

A


In [9]:
#WAPP That has class Point and location as Child class of point find reflection of point about x axis
#reflection method define in location class
class Point:
    def __init__(self,x,y):
        self.x=x
        self.y=y
class Location(Point):
    def reflection(self):
        return self.x ,0-self.y
l=Location(2,-2)
print(l.reflection())

(2, 2)


In [10]:
class Parent:
    def f1(self):
        print("Parent 1")
class Parent1():
    def f2(self):
        print("Parent 2")
class Parent2():
    def f3(self):
        print("Parent 3")
class Child(Parent,Parent1,Parent2):  #Jo parent phele order me milega ussika method print karayega 
    def f4(self):
        print("Child")
c=Child()
c.f1()
c.f2()
print(Child.__mro__)


Parent 1
Parent 2
(<class '__main__.Child'>, <class '__main__.Parent'>, <class '__main__.Parent1'>, <class '__main__.Parent2'>, <class 'object'>)


In [11]:
class Parent:
    def display(self):
        print("Hello Parent")
class Child(Parent):
    def display(self):
        super().display()
        print("Hello Child")
c = Child()
c.display()

Hello Parent
Hello Child


In [14]:
# Implement the following heirarchy create class called staff having name and salary as its attribute
# Derived class teaching has subject name as its attribute and non teaching class department name as its attribute
# the derive class methods override the methods of the base class
class Staff:
    def __init__(self,name,salary):
        self.name = name
        self.salary = salary
    def display(self):
        print("Name:",self.name)
        print("Salary:",self.salary)
class Teaching(Staff):
    def __init__(self,name,salary,subject):
        super().__init__(name,salary)
        self.subject = subject
    def display(self):
        super().display()
        print("Subject:",self.subject)
class NonTeaching(Staff):
    def __init__(self,name,salary,department):
        super().__init__(name,salary)
        self.department = department
    def display(self):
        super().display()
        print("Department:",self.department)
t = Teaching("ABP",100000,"Physics")
n = NonTeaching("Hitesh",10,"Cleaning")
t.display()
n.display()

Name: ABP
Salary: 100000
Subject: Physics
Name: Hitesh
Salary: 10
Department: Cleaning


In [20]:
# wap that has classes such as student,course,department,enroll and this should be displayed:
#     Raj with roll no 101 has enrolled for fcsp-1 in ce department
class Department(Course):
    def __init__(self,dept):
        self.dept = dept
class Course(Department):
    def __init__(self,course,dept):
        super().__init__(dept)
        self.course = course
class Student:
    def __init__(self,name,rollno):
        self.name = name
        self.rollno = rollno
class Enroll(Student,Course):
    def __init__(self,name,rollno,course,dept):
        Student.__init__(self,name,rollno)
        Course.__init__(self,course,dept)
    def display(self):
        print(f"{self.name} with rollno {self.rollno} has enrolled for {self.course} in {self.dept} department")
e = Enroll("Raj","101","FCSP-1","CE")
e.display()

Raj with rollno 101 has enrolled for FCSP-1 in CE department


In [6]:
# Create class called Stduent having name and email as its attribute
# create another class called PHDguide should have 4 methods
# constructor,display,add,remove
# In phd class having name email and student as its attributes
class Student:
    def __init__(self,name,email):
        self.name = name
        self.email = email
class PhdGuide:
    def __init__(self):
        self.l = []
    def add(self,st):
        self.l.append(st.name)
    def remove(self,name):
        self.l.remove(name)
    def display(self):
        for i in self.l:
            print(i)
a = Student("Raj","raj@123")
b = Student("Sunny","sunny@456")
c = Student("Mohan","mohan@345")
p = PhdGuide()
p.add(a)
p.add(b)
p.add(c)
p.display()
p.remove("Raj")
p.display()

Raj
Sunny
Mohan
Sunny
Mohan


In [12]:
# Numpy arrays
# create numpy
import numpy as np
a = np.array([1,2,3,4])
print(a)
#Dimension in array
#0D Array Individual values are counted as 0d array
#1D Array (above example is 1d array)
#2D Array
b = np.array([[1,2],[3,4],[5,6]])
print(b)
#3D Array
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)
#Higher dimensional array
d = np.array([1,2,3,4],ndmin= 5)
print(d)
print(d.ndim) #ndmin creates array of n dimensions and ndim returns number of dimensions of specific array

[1 2 3 4]
[[1 2]
 [3 4]
 [5 6]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[[[1 2 3 4]]]]]
5


In [35]:
#Numpy array slicing
import numpy as np
a = np.array([1,2,3,4,5,6,7])
print("*********** 1D Array ***************")
print(a[2:5])
print(a[-3:-1])
print(a[-2::-2])
print(a[5::-2])
print("*********** 2D Array ***************")
b = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(b[1,1:4])
print(b[:,2])
print(b[:,-2:0:-1])
print(b[:,3:0:-1])

*********** 1D Array ***************
[3 4 5]
[5 6]
[6 4 2]
[6 4 2]
*********** 2D Array ***************
[7 8 9]
[3 8]
[[4 3 2]
 [9 8 7]]
[[4 3 2]
 [9 8 7]]
